routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
/**
 * Группа маршрутов для панели администратора
 */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::resource('/polyathlon', 'PolyathlonController', ['as' => 'admin']);
    Route::resource('/specialty', 'SpecialtyController', ['as' => 'admin']);
    Route::resource('/group', 'GroupController', ['as' => 'admin']);
    Route::resource('/teacher', 'TeacherController', ['as' => 'admin']);
    Route::resource('/discipline', 'DisciplineController', ['as' => 'admin']);
    Route::resource('/classroom', 'ClassroomController', ['as' => 'admin']);
    Route::resource('/lesson', 'LessonController', ['as' => 'admin']);
    Route::resource('/replacement', 'ReplacementController', ['as' => 'admin']);
});

Auth::routes();

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    /**
     * Атрибуты, которые можно использовать массового заполнения.
     *
     * @var array
     */
    protected $fillable = [
        'specialty', 'course', 'full_time',
    ];
}

app/Http/Controllers/Admin/GroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Group;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Group::orderBy('course')->get();
        return view('admin.groups.index', [
            'groups' => $groups,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.groups.create', [
            'group' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Group::create($request->all());
        return redirect()->route('admin.group.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function show(Group $group)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function edit(Group $group)
    {
        return view('admin.groups.edit', [
            'group' => $group,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group)
    {
        $group->update($request->all());
        return redirect()->route('admin.group.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function destroy(Group $group)
    {
        $group->delete();
        return redirect()->route('admin.group.index');
    }
}

resources/views/admin/groups/create.blade.php
@extends('layouts.admin')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.groups.partials.header')
    <h3>Добавить группу</h3>
    <div>
        <form action="{{route('admin.group.store')}}" method="post">
            {{ csrf_field() }}
            @include('admin.groups.partials.form')
        </form>
    </div>
</main>

@endsection

resources/views/admin/groups/edit.blade.php
@extends('layouts.admin')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.groups.partials.header')
    <h3>Редактировать группу</h3>
    <div>
        <form action="{{route('admin.group.update', $group)}}" method="post">
            {{ method_field('put')}}
            {{ csrf_field() }}
            @include('admin.groups.partials.form')
        </form>
    </div>
</main>

@endsection

resources/views/admin/groups/index.blade.php
@extends('layouts.admin')

@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.groups.partials.header')

    <h3>Список групп</h3>
    <div class="table-responive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Специальность</th>
                    <th>Курс</th>
                    <th>Очное/Заочное</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @forelse ($groups as $key => $group)
                <tr>
                    <td>{{$group->specialty}}</td>
                    <td>{{$group->course}}</td>
                    <td>{{$group->full_time}}</td>
                    <td class="text-right">
                        <form action="{{route('admin.group.destroy', $group)}}" method="post">
                            {{ method_field('delete') }}
                            {{ csrf_field() }}

                            <a class="btn btn-sm btn-outline-primary" href="{{route('admin.group.edit', $group)}}">
                                <span data-feather="edit-2"></span>
                            </a>

                            <button type="submit" class="btn btn-sm btn-outline-danger">
                                <span data-feather="x"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                @empty
                    <h2>Данные отстствуют</h2>
                @endforelse
            </tbody>
        </table>
    </div>
</main>
@endsection