routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
/**
 * Группа маршрутов для панели администратора
 */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::resource('/polyathlon', 'PolyathlonController', ['as' => 'admin']);
    Route::resource('/specialty', 'SpecialtyController', ['as' => 'admin']);
    Route::resource('/group', 'GroupController', ['as' => 'admin']);
    Route::resource('/teacher', 'TeacherController', ['as' => 'admin']);
    Route::resource('/discipline', 'DisciplineController', ['as' => 'admin']);
    Route::resource('/classroom', 'ClassroomController', ['as' => 'admin']);
    Route::resource('/lesson', 'LessonController', ['as' => 'admin']);
    Route::resource('/replacement', 'ReplacementController', ['as' => 'admin']);
});

Auth::routes();

app/Specialty.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Specialty extends Model
{
    /**
     * Атрибуты, которые можно использовать массового заполнения.
     *
     * @var array
     */
    protected $fillable = [
        'number', 'name', 'abbreviation',
    ];
}

app/Http/Controllers/Admin/SpecialtyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Specialty;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SpecialtyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $specialties = Specialty::orderBy('number')->get();
        return view('admin.specialties.index', [
            'specialties' => $specialties,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.specialties.create', [
            'specialty' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Specialty::create($request->all());
        return redirect()->route('admin.specialty.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Specialty  $specialty
     * @return \Illuminate\Http\Response
     */
    public function show(Specialty $specialty)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Specialty  $specialty
     * @return \Illuminate\Http\Response
     */
    public function edit(Specialty $specialty)
    {
        return view('admin.specialties.edit', [
            'specialty' => $specialty,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Specialty  $specialty
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Specialty $specialty)
    {
        $specialty->update($request->all());
        return redirect()->route('admin.specialty.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Specialty  $specialty
     * @return \Illuminate\Http\Response
     */
    public function destroy(Specialty $specialty)
    {
        $specialty->delete();
        return redirect()->route('admin.specialty.index');
    }
}

resources/views/admin/specialties/create.blade.php
@extends('layouts.admin')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.specialties.partials.header')
    <h3>Добавить специальность</h3>
    <div>
        <form action="{{route('admin.specialty.store')}}" method="post">
            {{ csrf_field() }}
            @include('admin.specialties.partials.form')
        </form>
    </div>
</main>

@endsection

resources/views/admin/specialties/edit.blade.php
@extends('layouts.admin')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.specialties.partials.header')
    <h3>Редактировать специальность</h3>
    <div>
        <form action="{{route('admin.specialty.update', $specialty)}}" method="post">
            {{ method_field('put')}}
            {{ csrf_field() }}
            @include('admin.specialties.partials.form')
        </form>
    </div>
</main>

@endsection

resources/views/admin/specialties/index.blade.php
@extends('layouts.admin')

@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.specialties.partials.header')

    <h3>Список специальностей</h3>
    <div class="table-responive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Номер специальности</th>
                    <th>Название специальности</th>
                    <th>Аббревиатура</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @forelse ($specialties as $key => $specialty)
                <tr>
                    <td>{{$specialty->number}}</td>
                    <td>{{$specialty->name}}</td>
                    <td>{{$specialty->abbreviation}}</td>
                    <td class="text-right">
                        <form action="{{route('admin.specialty.destroy', $specialty)}}" method="post">
                            {{ method_field('delete') }}
                            {{ csrf_field() }}

                            <a class="btn btn-sm btn-outline-primary" href="{{route('admin.specialty.edit', $specialty)}}">
                                <span data-feather="edit-2"></span>
                            </a>

                            <button type="submit" class="btn btn-sm btn-outline-danger">
                                <span data-feather="x"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                @empty
                    <h2>Данные отстствуют</h2>
                @endforelse
            </tbody>
        </table>
    </div>
</main>
@endsection