routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
/**
 * Группа маршрутов для панели администратора
 */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::resource('/polyathlon', 'PolyathlonController', ['as' => 'admin']);
    Route::resource('/specialty', 'SpecialtyController', ['as' => 'admin']);
    Route::resource('/group', 'GroupController', ['as' => 'admin']);
    Route::resource('/teacher', 'TeacherController', ['as' => 'admin']);
    Route::resource('/discipline', 'DisciplineController', ['as' => 'admin']);
    Route::resource('/classroom', 'ClassroomController', ['as' => 'admin']);
    Route::resource('/lesson', 'LessonController', ['as' => 'admin']);
    Route::resource('/replacement', 'ReplacementController', ['as' => 'admin']);
});

Auth::routes();

app/Classroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Classroom extends Model
{
    /**
     * Атрибуты, которые можно использовать массового заполнения.
     *
     * @var array
     */
    protected $fillable = [
        'number', 'corpus', 'projector', 'screen', 'notice', 'places',
    ];
}

app/Http/Controllers/Admin/ClassroomController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Classroom;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClassroomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $classrooms = Classroom::orderBy('number')->get();
        return view('admin.classrooms.index', [
            'classrooms' => $classrooms,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.classrooms.create', [
            'classroom' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Classroom::create($request->all());
        return redirect()->route('admin.classroom.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Classroom  $classroom
     * @return \Illuminate\Http\Response
     */
    public function show(Classroom $classroom)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Classroom  $classroom
     * @return \Illuminate\Http\Response
     */
    public function edit(Classroom $classroom)
    {
        return view('admin.classrooms.edit', [
            'classroom' => $classroom,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Classroom  $classroom
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Classroom $classroom)
    {
        $classroom->update($request->all());
        return redirect()->route('admin.classroom.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Classroom  $classroom
     * @return \Illuminate\Http\Response
     */
    public function destroy(Classroom $classroom)
    {
        $classroom->delete();
        return redirect()->route('admin.classroom.index');
    }
}

resources/views/admin/classrooms/create.blade.php
@extends('layouts.admin')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.classrooms.partials.header')
    <h3>Добавить аудиторию</h3>
    <div>
        <form action="{{route('admin.classroom.store')}}" method="post">
            {{ csrf_field() }}
            @include('admin.classrooms.partials.form')
        </form>
    </div>
</main>

@endsection

resources/views/admin/classrooms/edit.blade.php
@extends('layouts.admin')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.classrooms.partials.header')
    <h3>Редактировать аудиторию</h3>
    <div>
        <form action="{{route('admin.classroom.update', $classroom)}}" method="post">
            {{ method_field('put')}}
            {{ csrf_field() }}
            @include('admin.classrooms.partials.form')
        </form>
    </div>
</main>

@endsection

resources/views/admin/classrooms/index.blade.php
@extends('layouts.admin')

@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.classrooms.partials.header')

    <h3>Список аудиторий</h3>
    <div class="table-responive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Номер аудитории</th>
                    <th>Корпус</th>
                    <th>Количество мест</th>
                    <th>Примечание</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @forelse ($classrooms as $key => $classroom)
                <tr>
                    <td>{{$classroom->number}}</td>
                    <td>{{$classroom->corpus}}</td>
                    <td>{{$classroom->places}}</td>
                    <td>{{$classroom->notice}}</td>
                    <td class="text-right">
                        <form action="{{route('admin.classroom.destroy', $classroom)}}" method="post">
                            {{ method_field('delete') }}
                            {{ csrf_field() }}

                            <a class="btn btn-sm btn-outline-primary" href="{{route('admin.classroom.edit', $classroom)}}">
                                <span data-feather="edit-2"></span>
                            </a>

                            <button type="submit" class="btn btn-sm btn-outline-danger">
                                <span data-feather="x"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                @empty
                    <h2>Данные отстствуют</h2>
                @endforelse
            </tbody>
        </table>
    </div>
</main>
@endsection