routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
/**
 * Группа маршрутов для панели администратора
 */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::resource('/polyathlon', 'PolyathlonController', ['as' => 'admin']);
    Route::resource('/specialty', 'SpecialtyController', ['as' => 'admin']);
    Route::resource('/group', 'GroupController', ['as' => 'admin']);
    Route::resource('/teacher', 'TeacherController', ['as' => 'admin']);
    Route::resource('/discipline', 'DisciplineController', ['as' => 'admin']);
    Route::resource('/classroom', 'ClassroomController', ['as' => 'admin']);
    Route::resource('/lesson', 'LessonController', ['as' => 'admin']);
    Route::resource('/replacement', 'ReplacementController', ['as' => 'admin']);
});

Auth::routes();

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    /**
     * Атрибуты, которые можно использовать массового заполнения.
     *
     * @var array
     */
    protected $fillable = [
        'weekday', 'number', 'group', 'teacher', 'discipline', 'classroom', 'subgroup',
    ];
}

app/Http/Controllers/Admin/LessonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Lesson;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lessons = Lesson::all();
        return view('admin.lessons.index', [
            'lessons' => $lessons,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.lessons.create', [
            'lesson' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Lesson::create($request->all());
        return redirect()->route('admin.lesson.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function show(Lesson $lesson)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function edit(Lesson $lesson)
    {
        return view('admin.lessons.edit', [
            'lesson' => $lesson,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lesson $lesson)
    {
        $lesson->update($request->all());
        return redirect()->route('admin.lesson.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lesson $lesson)
    {
        $lesson->delete();
        return redirect()->route('admin.lesson.index');
    }
}

resources/views/admin/lessons/create.blade.php
@extends('layouts.admin')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.lessons.partials.header')
    <h3>Добавить урок</h3>
    <div>
        <form action="{{route('admin.lesson.store')}}" method="post">
            {{ csrf_field() }}
            @include('admin.lessons.partials.form')
        </form>
    </div>
</main>

@endsection

resources/views/admin/lessons/edit.blade.php
@extends('layouts.admin')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.lessons.partials.header')
    <h3>Редактировать</h3>
    <div>
        <form action="{{route('admin.lesson.update', $lesson)}}" method="post">
            {{ method_field('put')}}
            {{ csrf_field() }}
            @include('admin.lessons.partials.form')
        </form>
    </div>
</main>

@endsection

resources/views/admin/lessons/index.blade.php
@extends('layouts.admin')

@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    @include('admin.lessons.partials.header')

    <h3>Список</h3>
    <div class="table-responive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>День недели</th>
                    <th>Номер урока</th>
                    <th>Группа</th>
                    <th>Преподаватель</th>
                    <th>Дисциплина</th>
                    <th>Аудитория</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @forelse ($lessons as $key => $lesson)
                <tr>
                    <td>{{$lesson->weekday}}</td>
                    <td>{{$lesson->number}}</td>
                    <td>{{$lesson->group}}</td>
                    <td>{{$lesson->teacher}}</td>
                    <td>{{$lesson->discipline}}</td>
                    <td>{{$lesson->classroom}}</td>
                    <td class="text-right">
                        <form action="{{route('admin.lesson.destroy', $lesson)}}" method="post">
                            {{ method_field('delete') }}
                            {{ csrf_field() }}

                            <a class="btn btn-sm btn-outline-primary" href="{{route('admin.lesson.edit', $lesson)}}">
                                <span data-feather="edit-2"></span>
                            </a>

                            <button type="submit" class="btn btn-sm btn-outline-danger">
                                <span data-feather="x"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                @empty
                    <h2>Данные отстствуют</h2>
                @endforelse
            </tbody>
        </table>
    </div>
</main>
@endsection